# Generated by Django 5.0.3 on 2024-03-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'pe'), (1, 'doc'), (2, 'script')])),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField()),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'error'), (2, 'online')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('object', models.UUIDField()),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'finished'), (3, 'error')])),
                ('creation_ts', models.DateTimeField(auto_now_add=True)),
                ('completed_ts', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.IntegerField(choices=[(0, 'malicious'), (1, 'suspicious'), (2, 'clean')])),
                ('analyzers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.analyzer')),
                ('nodes', models.ManyToManyField(to='myapp.node')),
            ],
        ),
    ]
